Add Views
Odongo006/Rails_blog_App pull request #7
Opened 2023-06-28 22:49 UTC by Odongo006

# Hello

I hope this message finds you well. I am writing to submit a pull request for review of the project that I have just completed. I have implemented the design based on the provided sneak peek wireframes and focused on ensuring the functionality of the application, with styling being a nice-to-have secondary consideration at this stage.

## Project Requirements

1. Implement the design from the sneak peek wireframes.
2. Focus on making sure everything functions first (styling is secondary).
3. Note: Ignore login logic as we will be using Devise in the upcoming milestone.
4. Analyze the wireframes deeply to identify all necessary elements and user navigation between pages.
5. Utilize the methods created in the Blog App for processing data in models.
6. Populate the database with relevant data to see posts and comments.

The project has been developed with adherence to the above requirements, and I have thoroughly tested the functionality to ensure a smooth user experience. The completed wireframes include:

1. All Users Page Wireframe
2. Single User Page Wireframe
3. All Posts by a Given User Page Wireframe
4. Single Post Page Wireframe

I kindly request that you review the code, functionality, and implementation of the wireframes. Any feedback, suggestions, or improvements would be greatly appreciated to enhance the project.

Thank you in advance for taking the time to review my work. I am eager to receive your feedback and incorporate any necessary improvements. Should you have any questions or require further information, please feel free to reach out to me.

2023-06-28 23:41 UTC, Ismailco requested changes
### Hi @Odongo006, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 23:41 UTC, Ismailco commented on app/views/posts/index.html.erb
> +            <% post.comments.each do |comment| %>
- [ ] Kindly make sure to use the `recent_comments` method to render the last 5 comments in the posts index page

2023-06-28 23:41 UTC, Ismailco commented on app/views/users/index.html.erb
> +  <% end %>
- [ ] Kindly make sure the views of the app look like the provided wireframe

|Your website|Provided Wirframes|
|-|-|
|![Screenshot_20230629_003530](https://github.com/Odongo006/Rails_blog_App/assets/25227022/668ad737-9b38-46ca-86bd-0e5e9b371027)|![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_root_users.png)|

2023-06-28 23:41 UTC, Ismailco commented on app/views/users/show.html.erb
> +<% end %>
- [ ] Kindly make sure the views of the app look like the provided wireframe

|Your website|Provided Wirframes|
|-|-|
|![Screenshot_20230629_003537](https://github.com/Odongo006/Rails_blog_App/assets/25227022/f2b52399-f581-400b-84fe-a91509c4ae7f)|![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_page.png)|

2023-06-28 23:41 UTC, Ismailco commented on app/views/posts/index.html.erb
> +  </div>
- [ ] Kindly make sure the views of the app look like the provided wireframe

|Your website|Provided Wirframes|
|-|-|
|![Screenshot_20230629_003543](https://github.com/Odongo006/Rails_blog_App/assets/25227022/dca2300f-25be-4fe0-b094-685e31d67394)|![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_user_all_posts.png)|

2023-06-28 23:41 UTC, Ismailco commented on app/views/posts/show.html.erb
> +<%end%>
- [ ] Kindly make sure the views of the app look like the provided wireframe

|Your website|Provided Wirframes|
|-|-|
|![Screenshot_20230629_003549](https://github.com/Odongo006/Rails_blog_App/assets/25227022/239ed7de-e178-4385-a668-193242be9765)|![](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png)|

2023-06-29 00:59 UTC, TadesseDev requested changes
### Hi @Odongo006 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [x] Good job making most of the changes requested by the previous reviewer. 🙏


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- N/A



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 00:59 UTC, TadesseDev commented on app/views/posts/index.html.erb
> +            <% end %>
- [ ] Dear @Odongo006, Great job adding some of the changes, but as suggested by the previous reviewer, we need to use the [recent_comments](https://github.com/Odongo006/Rails_blog_App/blob/Views/app/models/post.rb) method that is defined for your posts inside the `Post` controller. This way we will render only the most recent comments.

2023-06-29 19:38 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉🍾**
Hello @Odongo006 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Good commit messages.
- Correct git-flow.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 07:01 UTC, merged